unit LevelF;

interface

uses
  SysUtils, Windows, Messages, Classes, Graphics, Controls,
  Forms, Dialogs, Menus;

type
  TForm1 = class(TForm)
    MainMenu1: TMainMenu;
    File1: TMenuItem;
    Exit1: TMenuItem;
    N1: TMenuItem;
    PrintSetup1: TMenuItem;
    Print1: TMenuItem;
    N2: TMenuItem;
    SaveAs1: TMenuItem;
    Save1: TMenuItem;
    Open1: TMenuItem;
    New1: TMenuItem;
    Edit1: TMenuItem;
    GoTo1: TMenuItem;
    Replace1: TMenuItem;
    Find1: TMenuItem;
    N4: TMenuItem;
    PasteSpecial1: TMenuItem;
    Paste1: TMenuItem;
    Copy1: TMenuItem;
    Cut1: TMenuItem;
    N5: TMenuItem;
    Undo1: TMenuItem;
    Saving1: TMenuItem;
    Printing1: TMenuItem;
    Clipboard1: TMenuItem;
    Pasting1: TMenuItem;
    Options1: TMenuItem;
    FirstGroup1: TMenuItem;
    SecondGroup1: TMenuItem;
    ThirdGroup1: TMenuItem;
    A1: TMenuItem;
    B1: TMenuItem;
    C1: TMenuItem;
    D1: TMenuItem;
    E1: TMenuItem;
    F1: TMenuItem;
    G1: TMenuItem;
    H1: TMenuItem;
    I1: TMenuItem;
    J1: TMenuItem;
    K1: TMenuItem;
    L1: TMenuItem;
    M1: TMenuItem;
    N6: TMenuItem;
    O1: TMenuItem;
    P1: TMenuItem;
    Q1: TMenuItem;
    A11: TMenuItem;
    A21: TMenuItem;
    A31: TMenuItem;
    A41: TMenuItem;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form1: TForm1;

implementation

{$R *.DFM}

end.
